### ISSUE TITLE
Issue in the metadata dumper

### ISSUE THREAD

**Issue by linus727** [merkeg/mangadex-archivist#1]
Hey, amazing project!
I have an issue in the metadata dumper, my cmd returns this error code after it scanned the first 290 entries:

Traceback (most recent call last):
  File "C:\Users\Linus\Desktop\Mangadex\mangadex-archivist-master\mangadex-archivist.py", line 117, in <module>
    mangalist = gather_manga_in_list()
  File "C:\Users\Linus\Desktop\Mangadex\mangadex-archivist-master\mangadex-archivist.py", line 66, in gather_manga_in_list
    "friendly_name": filename.clean_filename(manga_info["attributes"]["title"]["en"]).rstrip(' .')
KeyError: 'en'

**Comment by merkeg** [comment]
Hey,
this error is likely caused by a manga, that has no English title. I made an update to the script, it should now fallback to the title Japanese. If it doesn't have a Japanese name as well, it will default to the first in list. And if it has no title at all (which would be very strange), it will default to the manga id.

I don't have any manga in my list, that do not have an English name, so I could not test that myself. It is a shot in the dark, but it should work I guess.

**Comment by linus727** [comment]
I got this error now:

[Manga] Getting all manga reading status...
[Manga] Got 1148 manga, getting metadata for all manga...
Traceback (most recent call last):
  File "C:\Users\Linus\Desktop\mangadex-archivist-master\mangadex-archivist.py", line 131, in <module>
    mangalist = gather_manga_in_list()
  File "C:\Users\Linus\Desktop\mangadex-archivist-master\mangadex-archivist.py", line 71, in gather_manga_in_list
    manganame = list(manga_info["attributes"]["title"].values[0])
TypeError: 'builtin_function_or_method' object is not subscriptable
